lrug/lrug.org

source/meetings/2015/february/index.html.md
I'm guessing this was leftover from a copy and paste.
=> Remove stray 'Drinks'

data/members.json
Hi can you add me as a member?
=> Add Ben to members

source/meetings/2015/may/index.html.md
Added details of Rails New Way presentation.
=> Updated description of my talk

data/members.json
Mostly as a test of the Travis build trigger
=> Update my URL in members.json

source/meetings/2016/june/index.html.md
Likelihood of this having no typos in it.... place your bets.
=> Write up June 2016 meeting

lib/lrug_helpers.rb, source/layouts/base.erb
Part 1 of an attempt to address #54.  There's some extra detail in the commit messages for the curious, but you can try it out on our [staging site](http://new.lrug.org/).
=> Better unfurl

.travis.yml, Gemfile, Gemfile.lock, source/meetings/2016/november/index.html.md
We've got the registration page, and a couple of talks so this is enough to publish.
=> Nov 2016 meeting

source/meetings/2016/december/index.html.md
Haven't bothered adding a lanyrd link to this one as the service seems to be
forgotten :(  We'll see if anyone kicks up a fuss.
=> Write up Dec 2016 meeting

source/meetings/2017/february/index.html.md
Not ready for merging yet, but here’s some of what we need.
Needs speaker links and some updated patter — at the moment it’s just a
Frankenstein’s monster of previous announcements.
=> Add February 2017 meeting

source/meetings/2017/march/index.html.md
As @h-lame suggests, this is largely based on the existing meeting layouts.
=> Add details for 2017 march meeting

source/meetings/2017/may/index.html.md
Here are the details for the May meeting - wasn't entirely sure what the rules were for setting the updated_at, published_at, created_at so would be worth paying extra attention to that.
=> Add details for May 2017 meeting

source/meetings/2017/august/index.html.md
There's a sponsor to come, but I'm waiting for it to be confirmed before
adding them.
=> Add writeup of August 2017 meeting

source/meetings/2017/october/index.html.md
TODO: skillsmatter event link and details of talks
=> Add placeholder info for October 2017

source/meetings/2018/april/index.html.md
Well, what we have so far anyway.
=> Add April 2018 meeting details

data/sponsors.json, source/meetings/2018/june/index.html.md
Some details TBC (giveaway, skillsmatter link, Najaf Ali's talk writeup) 
so we're not yet fit for publication.
=> June 2018 meeting

source/meetings/2018/september/index.html.md
Skills Matter have changed the availability of the room.
=> Update talks time to 7pm from 8.30pm

data/sponsors.json, source/meetings/2018/november/index.html.md
Most of this was organised by @EllaNancyFay so she gets the created_by credit.
=> Add November 2018 meeting details

source/meetings/2019/march/index.html.md
Because we’re starting late, I think we plan to finish around 8:30pm.
=> Change expected end time of March meeting

source/meetings/2019/may/index.html.md
Included a Call For Talks as we're still thin on the ground.
=> Add first talk for May 2019 meeting

source/meetings/2018/december/index.html.md, source/meetings/2019/october/index.html.md/index.html.md
Write up meeting, and fix an incorrect sponsor for Dec 2018
=> October 2019

data/sponsors.json, source/meetings/2019/december/index.html.md
=> Dec 2019 meeting

data/sponsors.json, source/meetings/2020/march/index.html.md
Still have one (or two) talks to confirm, but this is enough to announce with.
=> March 2020 meeting

lib/lrug_helpers.rb, source/_sponsors.erb, source/meetings/2020/may/index.html.md
No hosts, no problem.
Two talks, more later, maybe
=> May 2020 meeting

source/meetings/2020/june/index.html.md
=> June 2020 meeting

data/coverage.json
…on writing well-behaved Unix utilities in Ruby.
=> Add Rob Miller's 2014-10-13 talk

data/coverage.json, source/meetings/2011/august/index.html.md, source/meetings/2015/march/index.html.md
* Add write-up for March 2015 meeting
* Use HTTPS URLs for August 2011 meeting
=> Add coverage to August 2011 and March 2015

data/coverage.json
...control of your code quality"
=> Fix link to April 2020 video, "How to take..

data/coverage.json, source/meetings/2010/february/index.html.md, source/meetings/2010/june/index.html.md, source/meetings/2016/october/index.html.md, source/meetings/2020/june/index.html.md
=> More meeting coverage

source/meetings/2020/september/index.html.md
=> Sept 2020 meeting

lib/lrug_helpers.rb, source/_footer.erb, source/_header.erb, source/_sponsors.erb, source/index.html.erb, source/layouts/base.erb, source/meetings/2020/september/index.html.md, source/meetings/_meeting.erb, source/stylesheets/all.css.scss, source/stylesheets/components/_content.scss, source/stylesheets/components/_footer.scss, source/stylesheets/components/_header.scss, source/stylesheets/components/_sponsors.scss
I searched for LRUG on DDG & we [weren't ranking very well](https://user-images.githubusercontent.com/325384/93709689-32f6d900-fb38-11ea-87d6-4e0add53b8bd.png). So I had a little investigation into what could be causing that :)
Our [lighthouse report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Flrug.org) showed we had some aspects we could improve upon:
I also ran the site through a [HTML Validator](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Flrug.org%2F) & noted we had room for improvement also.
Mostly I just went through and made the "quick win" changes, such as improving HTML validation & adding suitable metatags.
=> Performing Lighthouse SEO recommendations

data/coverage/2020.yml
Per email from Murray, added more resources and links cited in the talk. Also added slides.
=> Adding more links and resources for the jwt talk.

source/meetings/2021/february/index.html.md
3 talks so far, so definitely enough to publish with, but hopefully we can
add more over the next week.
=> Add Feb 2021 meeting & writeup

source/meetings/2021/april/index.html.md
Necessary to provide information about myself. Also includes links to
my slides and site resources in general.
- See commit for details.
Was talking to Murray by email about this so hope I've built out the template as you'd like it. If not, let me know and I'll rebase the feedback as necessary. :wink:
=> Added April 2021 meeting schedule

source/meetings/2021/april/index.html.md
Adding details on top of #148 and publishing the page
=> Publish April 2021 writeup

source/meetings/2021/june/index.html.md
Hello! I noticed two small typos in the June meeting post; this fixes them.
=> Fix typo in June meeting

source/meetings/2021/july/index.html.md
Two talks added, still waiting on details of one more.
=> Writing up July 2021 meeting

data/coverage/2021.yml
- Link to a talk the founder of Beam did. Thanks!!
=> Add link to Beam @ TEDx

data/coverage/2021.yml, source/meetings/2021/july/index.html.md
Also change the title of Rob Faldo's talk to reflect the title used on the
night.
=> Add video links to July 2021 talks

source/meetings/2021/september/index.html.md
=> September 2021 meeting

source/meetings/2021/october/index.html.md
Details of two talks, which TBH, is probably enough.
=> Add Oct 2021 meeting writeup

data/coverage/2021.yml
Adds coverage for October 2021 videos.
=> Add coverage for video links October 2021

data/coverage/2021.yml
Adds a link to the slides used as part of this presentation.
=> Add slides to "Failing Better" November 2021 talk

source/meetings/2021/december/index.html.md
Add the write up for the December 2021 meeting.
=> Create December 2021 meeting

source/meetings/2021/december/index.html.md
Correct the published_at and created_at values.
=> Correct published_at and created_at

data/coverage/2022.yml, source/meetings/2022/february/index.html.md
Adds the February 2022 videos and coverage.
=> February 2022 videos

data/coverage/2021.yml
Better late than never :sweat_smile:
=> Add slides link for Dec 2021 Junior Devs talk

deploy-lrug.cgi
Previously this would happily deploy an empty site
=> Only deploy if untar successful

data/sponsors.json, source/meetings/2022/september/index.html.md
=> Add write-up of Sept 2022 meeting

source/meetings/2022/october/index.html.md
No talk details yet, but venue + eventbrite are sorted.
=> Add placeholder for Oct 2022 meeting

source/meetings/2022/october/index.html.md
=> Add Paul Battley's talk to October 2022

data/coverage/2022.yml, source/meetings/2022/october/index.html.md
Just the videos.  Perhaps there will be more links later.
=> Adding coverage to October 2022

source/meetings/2022/november/index.html.md
=> Add Christian Bruckmayer's talk to Nov 2022 meeting

data/coverage/2022.yml, source/meetings/2022/november/index.html.md
We have the videos, but also slides for Stan and Christian's talks, which is nice.
=> Add coverage links to the Nov 2022 meeting

source/meetings/2023/february/index.html.md
I've added the single confirmed talk, but we may want to add a couple more before publishing?
=> Feb 2023 meeting details

source/meetings/2023/february/index.html.md
💁 This change fixes a tiny but crucial typo.
=> Fix incorrect year on February meeting

source/meetings/2023/february/index.html.md
- add matt feb 2023 talk
- Add Alfredo feb 2023 talk
- Add Fell's feb 2023 talk
=> more feb 2023 talks

data/coverage/2023.yml
: in unquoted strings confuse yaml
=> Quote strings to make yaml happy

source/meetings/2023/april/index.html.md
Adds the details for Stan Lo's April 2023 talk.
=> Add Stan Lo's talk for April 2023

source/meetings/2023/may/index.html.md
- meeting skeleton
- Added Gus' may 2023 talk
- add eventbrite
=> add may 2023

source/meetings/2023/june/index.html.md
This PR adds the 4th talk to the June 2023 write-up.
=> Add Shen's talk June 2023

data/sponsors.json, source/meetings/2023/august/index.html.md
Adds the august writeup with the first confirmed talk
=> august 2023

source/meetings/2023/august/index.html.md
=> Fix registration anchor for August 2023 meeting

data/sponsors.json, source/meetings/2023/october/index.html.md, source/meetings/2023/september/index.html.md
- Move borrow my doggy to october
- boilerplate details for september/october
- add smart/canva logos
- tweak and publish sept 2023
=> setup september

data/coverage/2023.yml, source/meetings/2023/september/index.html.md
Video link for Ju and as we didn't record Paul's talk we link to existing transcript and repo from the Brighton version.  Eventually we'll link to the Brighton video too once it's published.
=> Add coverage for sept 2023

data/sponsors.json, source/meetings/2023/october/index.html.md
Still pending confirmation from B&W and Rikke on venue + talk availability, but this'll do for now
=> Update some details of the Oct meeting page

source/meetings/2023/november/index.html.md
- fix talk title
- fix anchor name
=> fix nov2023 talk title

data/coverage/2023.yml, source/meetings/2023/november/index.html.md
This PR adds videos for November 2023.
=> Add videos for November 2023

data/coverage/2024.yml, source/meetings/2024/january/index.html.md
Video for Joels talk has a particularly choppy mic, but it seems ok with some estimated subtitles to cover the worst cutouts.
=> Add coverage links for Jan 2024

data/coverage/2024.yml, source/meetings/2024/january/index.html.md
- Adds link to slides pdf
- Adds a link to my github on the blog post history for the January 2024 meeting
=> Adding Info for LLGems talk from January

data/coverage/2024.yml, source/meetings/2024/march/index.html.md
also tidy up alexey's talk since he was sick & unable to present.
=> Add march 2024 videos

data/coverage/2024.yml, source/meetings/2024/february/index.html.md
* Add link to PDF of slides
* Add personal link to February 2024 talk page
=> Add more info for February 2024 devcontainers talk

source/meetings/2024/may/index.html.md
Placeholder for May meeting.
TODO:
=> Add placeholder for May 2024

source/meetings/2024/may/index.html.md
Since we had somebody ask for accessibility info and we know them, we are adding them for the next meeting, which is May 2024.
=> Add accessibility info for May 2024

data/sponsors.json, source/meetings/2024/june/index.html.md
We have one talk, but waiting for a confirmation on venue.
=> Add placeholder for June meeting

source/meetings/2024/july/index.html.md
One talk + venue - but hopefully we'll confirm the 2nd soon (it's also from a Cleo employee).
=> Add initial July 2024 page

source/meetings/2024/july/index.html.md
This PR adds the 2nd talk to the July 2024 meetup.
=> Add Lily Stoney talk July 2024

data/coverage/2024.yml, source/meetings/2024/july/index.html.md
Lily had to pull out because she was ill, but one of her colleagues, Joel, stepped up to offer a different talk in her place.
=> Add coverage for July 2024, and update talks list

source/meetings/2024/october/index.html.md
Jade Dickinson is giving a run through of her talk from RubyConf 2024
=> Add Jade to oct 2024 lineup

data/coverage/2024.yml, source/meetings/2024/september/index.html.md
Link to the videos:
https://assets.lrug.org/videos/2024/september/lily-stoney-from-spaghetti-to-lasagna-layering-your-code-with-ddd-lrug-sep-2024.mp4
https://assets.lrug.org/videos/2024/september/rachel-bingham-b-and-w-rewards-domains-events-and-ledgers-lrug-sep-2024.mp4
=> add septemeber 2024 videos link

data/sponsors.json, source/meetings/2024/december/index.html.md
1. Need confirmation from Intercom that we're locked in
2. Need confirmation from Intercom on the NDA folk have to sign (acceptance of which we can add to ticket tailor as a condition of getting a ticket)
3. Details from Clem of the 2nd talk
=> Add December meeting placeholder

source/meetings/2025/january/index.html.md
Currently it's a placeholder with a venue and a call to action instead of an agenda, but at least we have a venue!
=> Add Jan 2025 details

source/meetings/2025/january/index.html.md
It read like we had no talks, but we do!
=> Update "you?" section for Jan 2025 meeting

data/coverage/2025.yml, source/meetings/2025/february/index.html.md
Also tidying up a couple of titles based on the titles used on the night in the talks.
=> Add video links for all the Feb'25 lightning talks

data/coverage/2025.yml, source/meetings/2025/april/index.html.md
Video links for Mario & Maciej's talks at the April 2025 meeting.
=> Coverage for April 2025

data/sponsors.json, data/talks/2025.yml, source/meetings/2025/september/index.html.md.erb
- **add vonage to sponsors**
- **first details for september**
=> september 2025 meeting

source/meetings/2025/september/index.html.md.erb
=> Update the date of the september 2025 meeting

data/talks/2025.yml
new date doesn't work for this speaker
=> remove sept 2025 talk

data/talks/2025.yml, source/meetings/2025/october/index.html.md.erb
Firm details on venue and one talk, awaiting confirmation from venue on if they have a talk before promoting one of the other offers and announcing.
=> Oct 2025 meeting
