- .travis.yml
This pull request enables building the site on Travis, and then pushing the built files as a bzip2'd tar file back to GitHub.
Because of restrictions with Travis's "release" deploy mechanism, it will only push the file back up to GitHub when it's building a tag. I believe this is ultimately because GitHub itself will only accept an upload with a 'tag_name' parameter. So, in order to trigger an upload, you actually have to create a tag and push that, which means that merging a pull request won't automatically build and upload the site back as a release.
> Build on travis

- config.rb
This fixes a bug where the years are listed out of order in the "Archives By Year" sidebar.
> Sort the meeting archive years

- source/meetings/2017/may/index.html.md
Ken Fassone has drafted a blog post related to the talk he gave in May, and asked if we could publish the link to it.
> Add link to blog post for Ken Fassone's talk

- source/stylesheets/all.css
Adds some really basic print CSS in order to hide a sidebar when
printed (it adds no value to a printed page).
Also displays URLs when printed, making it easier for people who
print off an event page to get access to things like interactive
maps.
Everything is wrapped in a `@media print` declaration and gracefully
degrades (is ignored) by older browsers.
People unaware of where the event takes place or who like to scribble
notes next to talks will often print pages from the website, these changes
make that experience that little bit nicer without adding too much CSS.
> Adds Print CSS

- source/meetings/2018/february/index.html.md
5 talks so far of the recommended 8.  Enough to have the page look ok, and
we've got the link from Skills Matter so folk can start registering.
> Start writeup of Feb 2018 meeting

- .travis.yml
We were relying on lazyatom's fork of dpl so we could get the "overwrite" option
to let us upload our build artefact to the same file on the same branch each
time.  However, that [has been merged to upstream][travis-dpl-merge] so we no
longer need to rely on the branch.
[travis-dpl-merge]: https://github.com/travis-ci/dpl/pull/386
> Rely on default travis/dpl

- data/sponsors.json
- source/meetings/2018/july/index.html.md
This isn’t ready to be merged, because it’s still missing:
@h-lame, would you be willing to add the sponsor info please? I’ve sent the speaker details to Megan and will put the SM link in when she provides it.
> Add July meeting write-up

- source/meetings/2018/september/index.html.md
I've added links to the speaker's Twitter accounts when we had them, Skills Matter profile otherwise.
This includes the link to the Skills Matter event: https://skillsmatter.com/meetups/11273-lrug-london-ruby-user-group
> Add September 2018 meeting details

- deploy-lrug.cgi
This will avoid deploying the site if the build failed, even though doing so doesn't really harm things since it will just re-deploy the most recent successful build.
> Only deploy if the build was on master, and passed

- source/meetings/2019/august/index.html.md
We're missing the link to the skills matter page.
> Add details for August 2019 meeting

- data/sponsors.json
- lib/lrug_helpers.rb
- source/meetings/2019/november/index.html.md
- source/sponsors/index.html.md.erb
Adding them to sponsors.json then adding a `hosted_by` content part for it.
Also added a "these people have hosted us before when our main host couldn't" bit to http://lrug.org/sponsors - which reveals that the hosted_by stuff is a bit of a mess.
In a later PR we should come back to this to make `hosted_by` first class metadata like sponsors, not a content part.  We can also explicitly put SM on all the ones they hosted and get rid of the default.  As long as we have a template (e.g. copy last month :wink:) we should be fine.
> Add FT as nov 2019 host

- data/sponsors.json
- source/meetings/2020/february/index.html.md
Includes adding simply business (the hosts) to the sponsors data.  We
need to add:
before we're ready to publish.
> Add draft of Feb 2020 meeting write up

- config.rb
- data/coverage.json
- lib/lrug_extended_kramdown.rb
- lib/lrug_helpers.rb
- source/meetings/2011/april/index.html.md
- source/meetings/2011/may/index.html.md
- source/meetings/2013/october/index.html.md
- source/meetings/2020/april/index.html.md
- source/meetings/2020/february/index.html.md
- source/meetings/2020/may/index.html.md
- source/sponsors/index.html.md.erb
- source/stylesheets/all.css
Ever since lanyrd started to rot off the internet I've wanted to extract the coverage links we added to meetings we had on there and put that info onto lrug.org somehow.  Mostly this means links to the videos of each talk from the skills matter site, but occasionally we'd add links to blog posts or slides or whatever too.  I started a scraper some time ago when lanyrd briefly appeared online again, and was waiting for it to re-appear so I could add some tweaks, but it really doesn't seem like it will so I tried using web.archive.org to get a few extra pages.  The `data/coverage.json` is the result of that scraping.  Like the `data/sponsors.json` we already have I've added `{::coverage}` extension tag to kramdown for rendering stuff out of the new data file.
I've put this example up on the …
> Add coverage links

- source/_default_sidebar.md.erb
I was clicking around the site & I noticed that the last.fm link redirected to a page announcing the "Closure of Legacy Last.fm site pages" in 2018.
I went ahead and removed the other 404'ing links from the sidebar & renamed the section to be "Community" (Similar to https://ruby.org.au).
> Removing 404'ing links from sidebar

- source/_default_sidebar.md.erb
It looks like the previous link I added to the sidebar wasn't the most up to date 😕
https://www.eventbrite.com/o/london-ruby-user-group-8260020214 - Previous link
https://www.eventbrite.com/o/london-ruby-user-group-28936506513 - New (And I think correct) Link
I think I used one event links from within the site to populate that link, was totally my fault for not realising it didn't have any recent event listed.
> Updating sidebar to be the latest LRUG eventbrite group

- .travis.yml
- Gemfile
- Gemfile.lock
Pulled from https://github.com/lrug/lrug.org/pull/143
This updates the Ruby version used to 2.7.2. When I ran `bundle exec middleman build` locally the only warning was:
> middleman-core-4.3.11/lib/middleman-core/builder.rb:232: warning: URI.escape is obsolete
Which is currently expected ( https://github.com/middleman/middleman/issues/2312 ), so not a big worry :)
> Updating to ruby 2.7.2

- data/coverage/2021.yml
I believe that the coverage for Patricia's video is not showing on LRUG's website because, in the relevant .yml file, the key that represents the title's talk is missing the final 's', while in the 'title' key this final 's' is present. See screenshot below.
> Fix coverage for 1 november 2021 video

- source/.htaccess.erb
For better or worse readme.lrug.org takes styles from lrug.org and expects them to live at styles.css.  They haven't for a while, _and_ we recently put in place asset hashes so it's not a static URL.  However, we can use some redirection to make it so that it is.
> Put a redirect in place for styles.css

- .travis.yml
We specified our own bundle install step which means we don't install to the place that travis expects and so the cache step doesn't give us any advantage what-so-ever as we're not caching where our gems are.  Removing our install step (and thus using the default travis one for ruby + bundler) means we do install to the same place we're caching from and so our builds _should_ get faster.
See https://docs.travis-ci.com/user/caching/#bundler for more detail.
> Take advantage of travis's default bundle install for caching

- source/meetings/2022/january/index.html.md
This PR adds the categories for the January 2022 quiz, as well as a range for the number of questions in each category.
> Add the quiz's categories and # of questions

- data/coverage/2021.yml
This commit adds in a link to where a narrative on Ruby's coverage
module can be found, along with links to the slides, and the repository
that has the code examples. An additional link refers to a blog post
written about the topic.
Thanks again for having me!
> Add Presentation Resources For December Coverage Talk

- data/coverage/2022.yml
This change adds a link to the slides used for the Feb 2022 
lightning talk on The tale of the 60+ second page loads.
> Add slides to Feb 2022 coverage

- source/meetings/2022/october/index.html.md
This PR adds the first talk for October 2022.
> Add Paul Battley's talk to October 2022

- source/meetings/2022/october/index.html.md
Reverts lrug/lrug.org#235
I suspect that, due to my forgetting there is a CI on this repo and merging the PR right away, the CI then fails.
> Revert "Add Paul Battley's talk to October 2022"

- data/sponsors.json
- source/meetings/2022/november/index.html.md
The only thing missing is Zappi's logo in the `hosted by` section. I can ask for it later, while we publish the writeup on our website.
> Add November's meeting

- .travis.yml
- README.md
- deploy-lrug.cgi
When opening #245 I was surprised that our default branch is still called `master`; for starters, `main` is now the [default branch name](https://github.com/github/renaming/#new-repositories-use-main-as-the-default-branch-name) for GitHub repos, so `master` feels anachronistic in more ways than one.
I assume some external infrastructure might need to be updated to support this, and of course someone would need to actually do the branch rename somewhat synchronously with this PR being merged.
> Rename default branch to `main`

- source/meetings/2022/december/index.html.md
#245 added this note to the November meeting announcement in c84c43e729cbca8cc837d06203f1e47896868f4e, but #248 didn’t incorporate that change for December. We should say it every time so that it’s clear the pub part of the meeting isn’t exempt from the code of conduct.
> Add code of conduct note to the “Afterwards” part of the December 2022 announcement

- data/sponsors.json
- source/meetings/2023/january/index.html.md
Placeholder (for now) - includes venue details (unboxed) and eventbrite link.
Ready for @chrislo to populate with speakers once we've sorted them.
> Jan 2023 meeting

- data/coverage/2023.yml
- source/meetings/2023/january/index.html.md
It does what it says on the tin: associates each January 2023 talk to the relevant video I edited.
> Add videos for January 2023

- source/sponsors/index.html.md.erb
So we can link separately to people who provided venues and people who gave us other forms of sponsorship.
Required by lrug/lrug.github.io/pull/66
> Add heading to "other" sponsors

- source/meetings/2024/february/index.html.md
He's ill so it's deferred to March - when we pull the placeholder we'll grab the description from git.
> Remove Luke's talk from Feb 2024 meeting

- source/meetings/2024/march/index.html.md
This PR creates the meeting page for March 2024, with the 2 confirmed talks for which we currently have all the details we need.
> Create March 2024 meeting page

- source/meetings/2024/april/index.html.md
No talks yet 😬 but we think Canva will host us again.
Ticket tailor site is up, but it, like this, assumes Canva will host us.
> Add placeholder for April 2024

- data/coverage/2024.yml
- source/meetings/2024/february/index.html.md
We also change the title of Martin Tomov's talk to better match what he actually gave.
Audio on Paolo and Jay's talks isn't great - unfortunately it's poor mic technique (no blame, it's hard!) and nothing we can do really.
> Add video coverage for Feb 2024

- source/meetings/2024/may/index.html.md
In the `sponsors.json` file, Cleo's name is capitalised. This is why we are not seeing their logo on the meetup's page.
> Capitalise Cleo's name in `hosted_by` for May 2024

- source/meetings/2025/january/index.html.md
I have added Yevhenii's January 2025 talk, and I have fixed an incorrect mention to `January 2024`.
> Add yevhenii talk january 2025

- data/coverage/2024.yml
These are the links from #352, added as coverage data
> Add links to October 2024 Activity Pub

- data/redirects.json
This makes it easy to bring up the slides on a speaker's laptop
> redirect /intro-slides to the intro slides doc

- source/meetings/2025/february/index.html.md
He included it in the email where he offered the talk, so I assumed he wanted us to use it. He then got in touch to ask us to remove it, and I am obliging.
> Remove LinkedIn link for Zhiqiang Bian

- data/coverage/2025.yml
- source/meetings/2025/march/index.html.md
Includes a link to slides for Hemal's talk. He shared the PDF with us to host, which is unusual, but it's better to have the slides available via us, than not, so we've put them on assets.lrug.org just like the videos.
> Add coverage links for March 2025 talks

- Gemfile.lock
ostruct won't be a default in ruby 3.5
> Bump icalendar to avoid dep warning about ostruct

- .github/workflows/build-and-deploy.yml
According to GitHub's documentation, to manually run our deploy workflow, we need to configure said workflow to also run on the `workflow_dispatch` event.
> Manually run deploy workflow from GitHub

- data/sponsors.json
They complained that the resized png was too blurry.
> Replace logo for judge.me with the SVG one
